### ISSUE TITLE
Package vs repository name mismatch (singular Microgrid vs plural Microgrids)

### ISSUE THREAD

**Issue by pierre-haessig** [Microgrids-X/Microgrids.jl#1]
Repository name is Microgrid.jl, but main file is `src/Microgrids.jl` which defines the `module Microgrids`. It is also `Microgrids` in the `Project.toml` and therefore when `using Microgrids`. Should we rename the repository or renames all the files?

I've tried to see how other packages are names (e.g. https://github.com/topics/microgrid). I see mostly singular name, but it's not conclusive (microgrid is rarely used alone.)

**Comment by evelisea** [comment]
The repository was renamed.
